[platformio]
src_dir = .
default_envs = ex_diagnostic_s3

[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.311/platform-espressif32.zip
framework = arduino
monitor_speed = 115200
monitor_eol = LF
monitor_echo = yes
monitor_filters = send_on_enter, colorize
extra_scripts = pre:scripts/generate_version.py
build_flags =
  -std=c++17
  -Wall
  -Wextra
  -Werror=return-type
  -Iinclude
  -Iexamples
  -DCORE_DEBUG_LEVEL=0
build_src_filter =
  -<*>
  +<src/**>

[example_s3]
board = esp32-s3-devkitc-1
board_build.flash_size = 4MB
board_upload.flash_size = 4MB
board_build.partitions = default.csv
build_flags =
  ${env.build_flags}
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1

[example_s2]
board = esp32-s2-saola-1
board_build.flash_size = 4MB
board_upload.flash_size = 4MB
board_build.partitions = default.csv
board_upload.after_reset = no_reset_stub
build_flags =
  ${env.build_flags}
  -DARDUINO_USB_MODE=0
  -DARDUINO_USB_CDC_ON_BOOT=1

[env:ex_bringup_s3]
extends = example_s3
build_src_filter =
  ${env.build_src_filter}
  +<examples/01_basic_bringup/**>

[env:ex_bringup_s2]
extends = example_s2
build_src_filter =
  ${env.build_src_filter}
  +<examples/01_basic_bringup/**>

[env:ex_continuous_s3]
extends = example_s3
build_src_filter =
  ${env.build_src_filter}
  +<examples/02_continuous_sampling/**>

[env:ex_continuous_s2]
extends = example_s2
build_src_filter =
  ${env.build_src_filter}
  +<examples/02_continuous_sampling/**>

[env:ex_one_shot_s3]
extends = example_s3
build_src_filter =
  ${env.build_src_filter}
  +<examples/03_one_shot/**>

[env:ex_one_shot_s2]
extends = example_s2
build_src_filter =
  ${env.build_src_filter}
  +<examples/03_one_shot/**>

[env:ex_fault_diagnostics_s3]
extends = example_s3
build_src_filter =
  ${env.build_src_filter}
  +<examples/04_fault_diagnostics/**>

[env:ex_fault_diagnostics_s2]
extends = example_s2
build_src_filter =
  ${env.build_src_filter}
  +<examples/04_fault_diagnostics/**>

[env:ex_rtd_configuration_s3]
extends = example_s3
build_src_filter =
  ${env.build_src_filter}
  +<examples/05_rtd_configuration/**>

[env:ex_rtd_configuration_s2]
extends = example_s2
build_src_filter =
  ${env.build_src_filter}
  +<examples/05_rtd_configuration/**>

[env:ex_diagnostic_s3]
extends = example_s3
build_src_filter =
  ${env.build_src_filter}
  +<examples/06_diagnostic_cli/**>

[env:ex_diagnostic_s2]
extends = example_s2
build_src_filter =
  ${env.build_src_filter}
  +<examples/06_diagnostic_cli/**>
