/**
 * @file Version.h
 * @brief MAX31865 library version information.
 *
 * This file is AUTO-GENERATED by scripts/generate_version.py from library.json.
 * DO NOT EDIT MANUALLY. Update version in library.json instead.
 *
 * Generated: 2026-04-29 21:43:46
 * Git commit: fbe41ab (dirty)
 */

#pragma once

#include <stdint.h>

namespace MAX31865Version {

static constexpr uint16_t VERSION_MAJOR = 0;
static constexpr uint16_t VERSION_MINOR = 1;
static constexpr uint16_t VERSION_PATCH = 2;
static constexpr const char* VERSION = "0.1.2";
static constexpr uint32_t VERSION_CODE = 102;
static constexpr const char* BUILD_DATE = "2026-04-29";
static constexpr const char* BUILD_TIME = "21:43:46";
static constexpr const char* BUILD_TIMESTAMP = "2026-04-29 21:43:46";
static constexpr const char* GIT_COMMIT = "fbe41ab";
static constexpr const char* GIT_STATUS = "dirty";
static constexpr const char* VERSION_FULL = "0.1.2 (fbe41ab, 2026-04-29 21:43:46)";

}  // namespace MAX31865Version
