/**
 * @file Version.h
 * @brief MAX31865 library version information.
 *
 * This file is AUTO-GENERATED by scripts/generate_version.py from library.json.
 * DO NOT EDIT MANUALLY. Update version in library.json instead.
 *
 * Generated: 2026-05-01 12:04:57
 * Git commit: 96491cf (dirty)
 */

#pragma once

#include <stdint.h>

namespace MAX31865Version {

/// @brief Major version (breaking changes).
static constexpr uint16_t VERSION_MAJOR = 0;

/// @brief Minor version (new features, backward compatible).
static constexpr uint16_t VERSION_MINOR = 1;

/// @brief Patch version (bug fixes).
static constexpr uint16_t VERSION_PATCH = 2;

/// @brief Full version string (e.g., "1.2.3").
static constexpr const char* VERSION = "0.1.2";

/// @brief Encoded version for numeric comparison.
/// @note Format: MAJOR*10000 + MINOR*100 + PATCH.
static constexpr uint32_t VERSION_CODE = 102;

/// @brief Build date (YYYY-MM-DD).
static constexpr const char* BUILD_DATE = "2026-05-01";

/// @brief Build time (HH:MM:SS).
static constexpr const char* BUILD_TIME = "12:04:57";

/// @brief Full build timestamp.
static constexpr const char* BUILD_TIMESTAMP = "2026-05-01 12:04:57";

/// @brief Git commit hash (short).
static constexpr const char* GIT_COMMIT = "96491cf";

/// @brief Git working tree status ("clean" or "dirty").
static constexpr const char* GIT_STATUS = "dirty";

/// @brief Full version string with commit and build timestamp.
static constexpr const char* VERSION_FULL = "0.1.2 (96491cf, 2026-05-01 12:04:57)";

}  // namespace MAX31865Version
