/**
 * @file Version.h
 * @brief MAX31865 library version information.
 *
 * This file is AUTO-GENERATED by scripts/generate_version.py from library.json.
 * DO NOT EDIT MANUALLY. Update version in library.json instead.
 */

#pragma once

#include <stdint.h>

namespace MAX31865Version {

/// @brief Major version (breaking changes).
static constexpr uint16_t VERSION_MAJOR = 1;

/// @brief Minor version (new features, backward compatible).
static constexpr uint16_t VERSION_MINOR = 0;

/// @brief Patch version (bug fixes).
static constexpr uint16_t VERSION_PATCH = 0;

/// @brief Full version string (e.g., "1.2.3").
static constexpr const char* VERSION = "1.0.0";

/// @brief Encoded version for numeric comparison.
/// @note Format: MAJOR*10000 + MINOR*100 + PATCH
/// @note Example: version 1.2.3 = 10203
static constexpr uint32_t VERSION_CODE = 10000;

}  // namespace MAX31865Version
