#!/usr/bin/env python3
"""Generate or verify the tracked stable Version.h from library.json."""

from __future__ import annotations

import argparse
import json
import pathlib
import re
import subprocess

try:
    Import("env")  # type: ignore[name-defined]
except Exception:
    env = None


SEMVER = re.compile(r"^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)$")


def project_root() -> pathlib.Path:
    if env is not None:
        return pathlib.Path(str(env["PROJECT_DIR"]))
    return pathlib.Path(__file__).resolve().parents[1]


def read_version(root: pathlib.Path) -> tuple[str, int, int, int]:
    data = json.loads((root / "library.json").read_text(encoding="utf-8"))
    version = data.get("version")
    if not isinstance(version, str):
        raise ValueError("library.json version must be a string")
    match = SEMVER.fullmatch(version)
    if match is None:
        raise ValueError("library.json version must be a three-part SemVer")
    major, minor, patch = (int(value) for value in match.groups())
    if major > 65535 or minor > 65535 or patch > 65535:
        raise ValueError("Version components must fit uint16_t")
    return version, major, minor, patch


def render(root: pathlib.Path) -> str:
    version, major, minor, patch = read_version(root)
    return f'''/**
 * @file Version.h
 * @brief MAX31865 library version information.
 *
 * This file is AUTO-GENERATED by scripts/generate_version.py from library.json.
 * DO NOT EDIT MANUALLY. Update version in library.json instead.
 */

#pragma once

#include <stdint.h>

namespace MAX31865Version {{

/// @brief Major version (breaking changes).
static constexpr uint16_t VERSION_MAJOR = {major};

/// @brief Minor version (new features, backward compatible).
static constexpr uint16_t VERSION_MINOR = {minor};

/// @brief Patch version (bug fixes).
static constexpr uint16_t VERSION_PATCH = {patch};

/// @brief Full version string (e.g., "1.2.3").
static constexpr const char* VERSION = "{version}";

/// @brief Encoded version for numeric comparison.
/// @note Format: MAJOR*10000 + MINOR*100 + PATCH
/// @note Example: version 1.2.3 = 10203
static constexpr uint32_t VERSION_CODE = {major * 10000 + minor * 100 + patch};

}}  // namespace MAX31865Version
'''


def version_header(root: pathlib.Path) -> pathlib.Path:
    return root / "include" / "MAX31865" / "Version.h"


def generate(root: pathlib.Path) -> None:
    destination = version_header(root)
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(render(root), encoding="utf-8", newline="\n")
    print(f"Generated {destination}")


def check(root: pathlib.Path) -> None:
    destination = version_header(root)
    expected = render(root)
    try:
        actual = destination.read_text(encoding="utf-8")
    except OSError as exc:
        raise RuntimeError(f"could not read generated Version.h: {exc}") from exc
    if actual != expected:
        raise RuntimeError(
            "Version.h is stale; run python scripts/generate_version.py --generate"
        )
    print("Version.h generation check PASSED")


def _cpp_string_literal(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'\\"{escaped}\\"'


def _append_cli_build_metadata(root: pathlib.Path) -> None:
    if env is None:
        return
    pioenv = str(env.get("PIOENV", ""))
    if not pioenv.startswith("ex_diagnostic_"):
        return
    try:
        commit_result = subprocess.run(
            ["git", "rev-parse", "--short=12", "HEAD"],
            cwd=root,
            capture_output=True,
            text=True,
            timeout=2,
            check=False,
        )
        status_result = subprocess.run(
            ["git", "status", "--porcelain"],
            cwd=root,
            capture_output=True,
            text=True,
            timeout=2,
            check=False,
        )
        commit = (
            commit_result.stdout.strip()
            if commit_result.returncode == 0
            else "unknown"
        ) or "unknown"
        status = (
            "dirty" if status_result.stdout.strip() else "clean"
        ) if status_result.returncode == 0 else "unknown"
    except Exception:
        commit, status = "unknown", "unknown"
    env.Append(
        CPPDEFINES=[
            ("MAX31865_CLI_GIT_COMMIT", _cpp_string_literal(commit)),
            ("MAX31865_CLI_GIT_STATUS", _cpp_string_literal(status)),
            (
                "MAX31865_CLI_TARGET",
                _cpp_string_literal(
                    "esp32-s2" if pioenv.endswith("_s2") else "esp32-s3"
                ),
            ),
            ("MAX31865_CLI_FRAMEWORK", _cpp_string_literal("arduino")),
            ("MAX31865_CLI_BUILD_KIND", _cpp_string_literal("diagnostic_cli")),
        ]
    )


def command_line() -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--generate", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = parser.parse_args()
    root = project_root()
    if args.generate:
        generate(root)
    else:
        check(root)
    return 0


if env is not None:
    root = project_root()
    check(root)
    _append_cli_build_metadata(root)
elif __name__ == "__main__":
    raise SystemExit(command_line())
