#!/usr/bin/env python3
"""Generate include/MAX31865/Version.h from library.json."""

from __future__ import annotations

import json
import subprocess
from datetime import datetime
from pathlib import Path


ENV = None
try:
    Import("env")  # type: ignore[name-defined]
    ENV = env  # type: ignore[name-defined]
except Exception:
    ENV = None


def _project_root() -> Path:
    if ENV is not None:
        return Path(ENV["PROJECT_DIR"]).resolve()
    return Path(__file__).resolve().parents[1]


ROOT = _project_root()
LIBRARY_JSON = ROOT / "library.json"
VERSION_H = ROOT / "include" / "MAX31865" / "Version.h"


def _git(args: list[str], default: str) -> str:
    try:
        return subprocess.check_output(
            ["git", *args],
            cwd=ROOT,
            stderr=subprocess.DEVNULL,
            text=True,
        ).strip() or default
    except Exception:
        return default


def _parse_semver(version: str) -> tuple[int, int, int]:
    core = version.split("-", 1)[0].split("+", 1)[0]
    parts = core.split(".")
    major = int(parts[0]) if len(parts) > 0 and parts[0].isdigit() else 0
    minor = int(parts[1]) if len(parts) > 1 and parts[1].isdigit() else 0
    patch = int(parts[2]) if len(parts) > 2 and parts[2].isdigit() else 0
    return major, minor, patch


def main() -> None:
    metadata = json.loads(LIBRARY_JSON.read_text(encoding="utf-8"))
    version = metadata.get("version", "0.0.0")
    major, minor, patch = _parse_semver(version)
    version_code = major * 10000 + minor * 100 + patch
    now = datetime.now()
    build_date = now.strftime("%Y-%m-%d")
    build_time = now.strftime("%H:%M:%S")
    build_timestamp = f"{build_date} {build_time}"
    commit = _git(["rev-parse", "--short", "HEAD"], "unknown")
    status = "dirty" if _git(["status", "--porcelain", "--untracked-files=no"], "") else "clean"

    content = f'''/**
 * @file Version.h
 * @brief MAX31865 library version information.
 *
 * This file is AUTO-GENERATED by scripts/generate_version.py from library.json.
 * DO NOT EDIT MANUALLY. Update version in library.json instead.
 *
 * Generated: {build_timestamp}
 * Git commit: {commit} ({status})
 */

#pragma once

#include <stdint.h>

namespace MAX31865Version {{

static constexpr uint16_t VERSION_MAJOR = {major};
static constexpr uint16_t VERSION_MINOR = {minor};
static constexpr uint16_t VERSION_PATCH = {patch};
static constexpr const char* VERSION = "{version}";
static constexpr uint32_t VERSION_CODE = {version_code};
static constexpr const char* BUILD_DATE = "{build_date}";
static constexpr const char* BUILD_TIME = "{build_time}";
static constexpr const char* BUILD_TIMESTAMP = "{build_timestamp}";
static constexpr const char* GIT_COMMIT = "{commit}";
static constexpr const char* GIT_STATUS = "{status}";
static constexpr const char* VERSION_FULL = "{version} ({commit}, {build_timestamp})";

}}  // namespace MAX31865Version
'''
    VERSION_H.write_text(content, encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
else:
    main()
